---
title: "Investigating Racial Profiling"
subtitle: "MCMC Modeling for the NYC Stop-and-Frisk Policy"
author: "Chen Shi, Belle Xu"
date: "4/21/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(rstanarm)
library(bayesplot)
library(bayestestR)
library(bridgesampling)
library(logspline)
```

```{r}
stop <- read.table("stop-and-frisk.dat", header = TRUE)
```


# Exploratory Data Analysis

```{r fig.width=12, fig.height=4}
# Proportion of stops for each ethnicity in each precinct
stop %>% 
  mutate(eth = factor(eth, levels = c("3", "1", "2")),
         precinct = factor(precinct)) %>%
  group_by(eth, precinct) %>%
  mutate(stop_eth = sum(stops)) %>%
  ggplot(mapping = aes(x = precinct, y = stop_eth, fill = eth)) +
  geom_bar(position = "fill", stat = "identity") +
  geom_hline(yintercept = 1/3, linetype=5) +
  geom_hline(yintercept = 2/3, linetype=5) +
  labs(y = "Proportion of Stops", x = "Precinct", 
       title = "Proportion of Stops per Precinct by Ethnicity")+
  theme_bw() +
  theme(legend.position = "bottom") +
  scale_fill_discrete(name = "Ethnicity",
                      labels=c("White", "Black", "Hispanic"),
                      type = c("#b7ee47","#ff6b6b","#4ebaba"))
```

```{r fig.width=12, fig.height=4}
stop %>%
  mutate(eth = factor(eth, levels = c("3", "1", "2")),
         precinct = factor(precinct)) %>%
  group_by(eth, precinct) %>%
  mutate(crime_eth = sum(past.arrests)) %>%
  ggplot(mapping = aes(x = precinct, y = crime_eth, fill = eth)) +
  geom_bar(position = "fill", stat = "identity") +
  geom_hline(yintercept = 1/3, linetype=5) +
  geom_hline(yintercept = 2/3, linetype=5) +
  labs(title = "Proportion of Past Arrests per Precinct by Ethnicity",
       y = "Proportion of Past Arrests", x = "Precinct") +
  theme_bw() +
  theme(legend.position = "bottom") +
  scale_fill_discrete(name = "Ethnicity",
                      labels=c("White", "Black", "Hispanic"),
                      type = c("#b7ee47","#ff6b6b","#4ebaba"))
```

```{r fig.width=12, fig.height=4}
stop %>% 
  mutate(eth = factor(eth, levels = c("3", "1", "2")),
         precinct = factor(precinct)) %>%
  group_by(eth, precinct) %>%
  ggplot(mapping = aes(x = precinct, y = pop, fill = eth)) +
  geom_bar(position = "fill", stat = "identity") +
  geom_hline(yintercept = 1/3, linetype=5) +
  geom_hline(yintercept = 2/3, linetype=5) +
  labs(title = "Proportion of Population per Precinct by Ethnicity",
         y = "Proportion of Population", x = "Precinct") +
  theme_bw() +
  theme(legend.position = "bottom") +
  scale_fill_discrete(name = "Ethnicity",
                      labels=c("White", "Black", "Hispanic"),
                      type = c("#b7ee47","#ff6b6b","#4ebaba"))
```


```{r fig.width=12, fig.height=4}
stop %>%
  mutate(eth = factor(eth, levels = c("3", "1", "2")),
         precinct = factor(precinct),
         crime = factor(crime)) %>%
  filter(eth == "1") %>%
  ggplot(mapping = aes(x = precinct, y = stops, fill = crime)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(title = "Proportion of Stops (Black) per Precinct by Crime Type",
       y = "Proportion of Stops", x = "Precinct") +
  theme_bw() +
  theme(legend.position = "bottom") +
  scale_fill_discrete(name = "Crime",
                      labels=c("Violent", "Weapons", "Property", "Drug"),
                      type = c("#25B388","#F26C24","#1C5DA6", "#F09A18"))
```
```{r fig.width=12, fig.height=4}
stop %>%
  mutate(eth = factor(eth, levels = c("3", "1", "2")),
         precinct = factor(precinct),
         crime = factor(crime)) %>%
  filter(eth == "1") %>%
  ggplot(mapping = aes(x = precinct, y = past.arrests, fill = crime)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(title = "Proportion of Past Arrests (Black) per Precinct by Crime Type", 
       y = "Proportion of Past Arrests", x = "Precinct") +
  theme_bw() +
  theme(legend.position = "bottom") +
  scale_fill_discrete(name = "Crime",
                      labels=c("Violent", "Weapons", "Property", "Drug"),
                      type = c("#25B388","#F26C24","#1C5DA6", "#F09A18"))
```

```{r fig.width=12, fig.height=4}
stop %>%
  mutate(eth = factor(eth, levels = c("3", "1", "2")),
         precinct = factor(precinct),
         crime = factor(crime)) %>%
  filter(eth == "2") %>%
  ggplot(mapping = aes(x = precinct, y = stops, fill = crime)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(title = "Proportion of Stops (Hispanic) per Precinct by Crime Type",
       y = "Proportion of Stops", x = "Precinct") +
  theme_bw() +
  theme(legend.position = "bottom") +
  scale_fill_discrete(name = "Crime",
                      labels=c("Violent", "Weapons", "Property", "Drug"),
                      type = c("#25B388","#F26C24","#1C5DA6", "#F09A18"))
```
```{r fig.width=12, fig.height=4}
stop %>%
  mutate(eth = factor(eth, levels = c("3", "1", "2")),
         precinct = factor(precinct),
         crime = factor(crime)) %>%
  filter(eth == "2") %>%
  ggplot(mapping = aes(x = precinct, y = past.arrests, fill = crime)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(title = "Proportion of Past Arrests (Hispanic) per Precinct by Crime Type", 
       y = "Proportion of Past Arrests", x = "Precinct") +
  theme_bw() +
  theme(legend.position = "bottom") +
  scale_fill_discrete(name = "Crime",
                      labels=c("Violent", "Weapons", "Property", "Drug"),
                      type = c("#25B388","#F26C24","#1C5DA6", "#F09A18"))
```

```{r fig.width=12, fig.height=4}
stop %>%
  mutate(eth = factor(eth, levels = c("3", "1", "2")),
         precinct = factor(precinct),
         crime = factor(crime)) %>%
  filter(eth == "3") %>%
  ggplot(mapping = aes(x = precinct, y = stops, fill = crime)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(title = "Proportion of Stops (White) per Precinct by Crime Type",
       y = "Proportion of Stops", x = "Precinct") +
  theme_bw() +
  theme(legend.position = "bottom") +
  scale_fill_discrete(name = "Crime",
                      labels=c("Violent", "Weapons", "Property", "Drug"),
                      type = c("#25B388","#F26C24","#1C5DA6", "#F09A18"))
```
```{r fig.width=12, fig.height=4}
stop %>%
  mutate(eth = factor(eth, levels = c("3", "1", "2")),
         precinct = factor(precinct),
         crime = factor(crime)) %>%
  filter(eth == "3") %>%
  ggplot(mapping = aes(x = precinct, y = past.arrests, fill = crime)) +
  geom_bar(position = "fill", stat = "identity") +
  labs(title = "Proportion of Past Arrests (White) per Precinct by Crime Type", 
       y = "Proportion of Past Arrests", x = "Precinct") +
  theme_bw() +
  theme(legend.position = "bottom") +
  scale_fill_discrete(name = "Crime",
                      labels=c("Violent", "Weapons", "Property", "Drug"),
                      type = c("#25B388","#F26C24","#1C5DA6", "#F09A18"))
```


```{r}
stop %>%
  mutate(eth = factor(eth, levels = c("3", "1", "2")),
         precinct = factor(precinct),
         crime = factor(crime)) %>%
  group_by(precinct) %>%
  mutate(total_pop = sum(pop) / 4,
         pop_prop = pop / total_pop,
         total_stop = sum(stops),
         stop_prop = stops / total_stop) %>%
  group_by(eth, precinct) %>%
  mutate(eth_stop = sum(stop_prop)) %>%
  filter(crime == 1) %>%
  ggplot(mapping = aes(x = pop_prop, y = eth_stop, color = eth)) +
  geom_point() + theme_bw()+
  labs(title = "Stop Proportion (All Stops) vs. Population Proportion per Precinct",
       x = "Population Proportion (per Precinct)", y = "Stop Proportion (All Stops)") + 
  scale_colour_discrete(name = "Ethnicity",
                      labels=c("White", "Black", "Hispanic"),
                      type = c("#9EBE00","#FD0006","#009B95"))
```
```{r}
stop %>%
  mutate(eth = factor(eth, levels = c("3", "1", "2")),
         precinct = factor(precinct),
         crime = factor(crime)) %>%
  group_by(precinct) %>%
  mutate(total_pop = sum(pop) / 4,
         pop_prop = pop / total_pop,
         total_arrest = sum(past.arrests),
         crime_prop = past.arrests / total_arrest) %>%
  group_by(eth, precinct) %>%
  mutate(eth_crime = sum(crime_prop)) %>%
  filter(crime == 1) %>%
  ggplot(mapping = aes(x = pop_prop, y = eth_crime, color = eth)) +
  geom_point() + theme_bw()+
  labs(title="Past Arrests Prop.(All Crimes) vs. Population Prop. per Precinct",
       x = "Population Proportion (per Precinct)",
       y = "Past Arrests Proportion (All Crimes)") + 
  scale_colour_discrete(name = "Ethnicity",
                      labels=c("White", "Black", "Hispanic"),
                      type = c("#9EBE00","#FD0006","#009B95"))
```

```{r}
## Data Cleaning 
total_crime <- stop %>%
  mutate(eth = factor(eth, levels = c("3", "1", "2")),
         precinct = factor(precinct),
         crime = factor(crime)) %>%
  group_by(precinct) %>%
  mutate(total_pop = sum(pop) / 4,
         pop_prop = pop / total_pop,
         total_arrest = sum(past.arrests),
         crime_prop = past.arrests / total_arrest) %>%
  mutate(past.arrests = if_else(past.arrests!= 0, past.arrests, as.integer(1)))
```

```{r}
mean(total_crime$stops)
var(total_crime$stops)
```


# Modeling
```{r}
model.1 <- stan_glm(data = total_crime,
                    formula = stops ~ eth * (pop_prop + crime) + pop_prop * crime,
                    family = neg_binomial_2(link = "log"),
                    offset = log(past.arrests),
                    seed = 360,
                    prior = cauchy(0, 2.5),
                    prior_intercept = cauchy(0, 2.5),
                    refresh = 0,
                   diagnostic_file = file.path(tempdir(), "glm1.csv"))
```

```{r}
model.2 <- stan_glm(data = total_crime,
                    formula = stops ~ eth * (crime_prop + pop_prop + crime) + 
                      pop_prop * crime_prop + pop_prop * crime +
                      crime_prop * crime,
                    family = neg_binomial_2(link = "log"),
                    prior = cauchy(0, 2.5),
                    prior_intercept = cauchy(0, 2.5),
                    seed = 360,
                    refresh = 0,
                   diagnostic_file = file.path(tempdir(), "glm2.csv"))
```

```{r}
model.3 <- stan_glm(data = total_crime,
                    formula = stops ~ log(past.arrests)+
                      eth * (pop_prop + crime) + pop_prop * crime,
                    family = neg_binomial_2(link = "log"),
                    prior = cauchy(0, 2.5),
                    prior_intercept = cauchy(0, 2.5),
                    seed = 360,
                    refresh = 0,
                   diagnostic_file = file.path(tempdir(), "glm3.csv"))
```

```{r}
rstanarm::loo_compare(loo(model.1), loo(model.2), loo(model.3))
```

```{r}
model.3.full <- stan_glm(data = total_crime,
                    formula = stops ~  log(past.arrests)+
                      eth * (pop_prop + crime) + pop_prop * crime+
                      eth*log(past.arrests) + pop_prop*log(past.arrests) +
                      crime*log(past.arrests),
                    family = neg_binomial_2(link = "log"),
                    prior = cauchy(0, 2.5),
                    prior_intercept = cauchy(0, 2.5),
                    seed = 360,
                    refresh = 0,
                   diagnostic_file = file.path(tempdir(), "glm3full.csv"))
```

```{r}
bayesfactor_models(model.3, model.3.full, denominator = model.3.full)
```

```{r}
rstanarm::loo_compare(loo(model.3), loo(model.3.full))
```

See diagnostic plots in the pdf file Diagnostic-Plots within this GitHub Repository. 

# Results

```{r fig.width=8, fig.height=8}
mcmc_areas(as.matrix(model.3.full), prob = 0.95, prob_outer = 1)
```
```{r}
round(coef(model.3.full), 3)
round(posterior_interval(model.3.full, prob = 0.95), 3)
```



