---
title: "360 Final Project"
author: "Group: Flora Shi, Belle Xu"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, message=F, warning=F, echo=F}
library(rstanarm)
library(rstan)
library(magrittr)
library(latex2exp)
library(tidyverse)
library(knitr)
library(broom)
library(patchwork)
library(ggplot2)
library(extraDistr)
library(coda)
library(EnvStats)
library(LearnBayes)
library(MASS)
library(ash)
library(loo)
require(bayesplot)
library(bayestestR)
library(bridgesampling)
library(logspline)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(fig.aligned = 'center', fig.width = 7, fig.height = 4)
```

```{r}
stop <- read.table("stop-and-frisk.dat", header = TRUE)
```


## Exploratory Data Analysis 

Exploratory data analysis should support project goals and help guide specification of model.
```{r}
#make categorical variables factor
stop <- stop %>%
  mutate(precinct = factor(precinct)) %>%
  mutate(eth = factor(eth, levels = c("3", "1", "2"))) %>%
  mutate(crime = factor(crime))

#crime rate for a certain crime for each eth in a certain precinct
stop <- stop %>% mutate(crime_rate = past.arrests/pop)
#compute population proportion with in each precinct
stop <- stop %>% group_by(precinct) %>%
  mutate(total_pop = sum(pop/4))
stop <- stop %>% mutate(pop_prop = pop/total_pop)
```


```{r}
#make a by-precinct dataframe
stop <- stop %>%
  group_by(precinct) %>%
  mutate(stops_in_precinct = sum(stops))

stops_by_precinct <- stop %>% distinct(stops_in_precinct) %>%
  pull(stops_in_precinct)
precinct <- seq(from = 1, to = 75, by = 1)
pop_by_precinct<- stop %>% group_by(precinct) %>%
  mutate(pop_in_precinct = sum(pop)) %>% 
  distinct(pop_in_precinct) %>%
  pull(pop_in_precinct)
by_precinct_df <- data.frame(pop_by_precinct = pop_by_precinct, 
                                 stops_by_precinct = stops_by_precinct, 
                                 precinct = as.factor(precinct))
by_precinct_df <- by_precinct_df %>%
  mutate(toHighlight = if_else(stops_by_precinct == min(stops_by_precinct)
                               | stops_by_precinct == max(stops_by_precinct),
                               "yes", "no"))
```




```{r, fig.width = 13, fig.height = 4}
#number of stops by precinct
ggplot(data = by_precinct_df,
       mapping = aes(x = precinct, y = stops_by_precinct, fill = toHighlight)) +
  geom_col() +
    scale_fill_manual(values= c("yes"="tomato", "no"="#a1a1a1"), guide = FALSE)+
  labs(title = "Number of Stops per Precinct", x = "Precinct Number (1 to 75)",
       y = "Number of Stops Recorded")
#Need interpretation
# get the max and min stops with function and just type it 
min(by_precinct_df$stops_by_precinct)
max(by_precinct_df$stops_by_precinct)
```
```{r}
#number of stops vs. precinct pop
ggplot(data = by_precinct_df,
       mapping = aes(x = pop_by_precinct, y =stops_by_precinct)) + 
  geom_point() + 
  labs(title = "Number of Stops vs. Population per Precinct", 
       x = "Population Count (per Precinct)", 
       y = "Number of Stops (per Precinct)") +
  geom_smooth(method = "lm", formula = y~x, se = FALSE)
#no obvious trend between population in precinct vs. stops in a precinct
#maybe weakly positive
```

```{r}
#number of stops for each ethnicity vs. 
#  population for each ethnicity per precinct

ggplot(data = stop, mapping = aes(x = pop, y = stops, colour = eth)) +
  geom_point() +
  labs(title = "Number of Stops vs. Population per Precinct by Ethnicity",
       x = "Population Count per Precinct by Ethnicity",
       y = "Number of Stops per Precinct by Ethnicity", 
       colour = "Ethnicity") + 
  scale_color_manual(values = c("#9EBE00","#FD0006","#009B95"),
                     labels = c("White", "Black", "Hispanic"))
#There does seem to be some trend because we can see that none of the 
#  points for the white population is in high number of stops 
#  despite having very high population
```

```{r}
#num of stops vs crime rate
ggplot(data = stop, mapping = aes(x = crime_rate, y = stops, colour = eth)) + 
  geom_point() + 
  labs(title = "Number of Stops vs. Crime Rate in the Past Year per Precinct by Ethnicity",
       x = "Crime Rate per Precinct by Ethnicity",
       y = "Number of Stops per Precinct by Ethnicity", 
       colour = "Ethnicity") + 
  scale_color_manual(values = c("#9EBE00","#FD0006","#009B95"),
                     labels = c("White", "Black", "Hispanic"))
#crime rate is generally low with a few exceptions; however black 
#  and hispanic stop count are still
#  a lot higher in low crime rate regions
```

```{r}
#get datasets for different crime types 
stop.1 <- stop %>% filter(crime == 1)
stop.2 <- stop %>% filter(crime == 2)
stop.3 <- stop %>% filter(crime == 3) 
stop.4 <- stop %>% filter(crime == 4)
#investigate mean and var of each stop 
Violence <- c(mean(stop.1$stops), var(stop.1$stops))
Weapon <- c(mean(stop.2$stops), var(stop.2$stops))
Property <- c(mean(stop.3$stops), var(stop.3$stops))
Drug <- c(mean(stop.4$stops), var(stop.4$stops))
df <- data.frame(Violence, Weapon, Property, Drug)
row.names(df) <- c("Mean", "Variance")
df
```

```{r}
#number of stops per crime for each ethnicity
ggplot(data = stop, mapping = aes(x = eth, y = stops, fill = crime)) +
  geom_col(position = "dodge") + 
  labs(title = "Number of Stops per Crime for each Ethnicity", 
       x = "Ethnicity", 
       y = "Number of Stops (per Crime)",
       fill = "Crime Type") + 
  scale_x_discrete(labels=c("3" = "White", "1" = "Black",
                              "2" = "Hispanic")) +
  scale_fill_manual(values = c("#25B388","#F26C24","#1C5DA6", "#F09A18"),
                     labels = c("Violent", "Weapon",
                                "Property", "Drug"))
#number of past arrests per crime for each ethnicity
ggplot(data = stop, mapping = aes(x = eth, y = past.arrests, fill = crime)) +
  geom_col(position = "dodge") + 
  labs(title = "Number of Past Arrests per Crime for each Ethnicity", 
       x = "Ethnicity", 
       y = "Number of Stops (per Crime)",
       fill = "Crime Type") + 
  scale_x_discrete(labels=c("3" = "White", "1" = "Black",
                              "2" = "Hispanic")) +
  scale_fill_manual(values = c("#25B388","#F26C24","#1C5DA6", "#F09A18"),
                     labels = c("Violent", "Weapon",
                                "Property", "Drug"))

#from the two plots above, the stop reasons and past arrests seem to have no relation
```

## Modeling 

### Rstan GLM

#### Violent Crimes 

```{r}
#glm for crime 1; done for testing only. don't repeat the code for other crimes yet. 
#assuming negative binom sampling model

stan.glm.1 <- stan_glm(data = stop.1,
                   formula = stops ~ crime_rate+ pop_prop+ eth+ crime_rate:eth+ 
                     pop_prop:eth + crime_rate:pop_prop,
                   family = neg_binomial_2,
                   seed = 360, 
                   prior = cauchy(0, 2.5), 
                   prior_intercept = cauchy(0, 2.5),
                   refresh = 0, 
                   diagnostic_file = file.path(tempdir(), "glm.csv"))

#no r-hat warning = converged. no ess warning = good enough ess. apparently divergent transitions can be ignored 
```

```{r}
#checking if adding/changing stuff will make the model better
stan.glm.2 <- stan_glm(data = stop.1,
                   formula = stops ~ past.arrests+ pop_prop+ eth+ 
                     past.arrests:eth+ pop_prop:eth + past.arrests:pop_prop,
                   family = neg_binomial_2, #how do I justify not having a prior? 
                   seed = 360,
                   refresh = 0,
                   diagnostic_file = file.path(tempdir(), "glm.csv"))
stan.glm.3 <- update(stan.glm.2, formula = stops ~ past.arrests+ pop+ eth+ 
                       past.arrests:eth+ pop:eth + past.arrests:pop,
                   diagnostic_file = file.path(tempdir(), "glm.csv"))
```


```{r}
set.seed(360)
bridge1 <- bridge_sampler(stan.glm.1)
bridge2 <- bridge_sampler(stan.glm.2)
bridge3 <- bridge_sampler(stan.glm.3)
a <- bf(bridge2, bridge1)
b <- bf(bridge2, bridge3)
c <- bf(bridge3, bridge2)
a$bf
b$bf
c$bf
```

```{r}
#look at coefficients
summary(stan.glm.1)
```
```{r}
#posterior distributions
mcmc_areas(as.matrix(stan.glm.1), prob = 0.95, prob_outer = 1)
round(coef(stan.glm.1), 3)
round(posterior_interval(stan.glm.1, prob = 0.95), 3)
```
 

```{r}
#posterior predictive check 
loo1 <- loo(stan.glm.1, save_psis = TRUE)
loo2 <- loo(stan.glm.2, save_psis = TRUE)
loo3 <- loo(stan.glm.3, save_psis = TRUE)
```
```{r}
rstanarm::loo_compare(loo1, loo2, loo3) #loo2 is the best. 
```
```{r}
#making sure that bayesian ver of AIC (pareto k) is good
loo1
```

```{r}
#check for outliers (if there are outliers, then post pred will be sensative to 1 observation)
plot(loo2, label_points = TRUE)
```

```{r}
#individual model diagnostics - stan.glm.1
y.postpred <- posterior_predict(stan.glm.1)
color_scheme_set("brightblue")
ppc_dens_overlay(stop.1$stops, y.postpred) + xlim(0, 1000) #xlim() truncates so that we focus on the part where x is less than 1000 
```


```{r}
pp_check(stan.glm.1, plotfun = "boxplot") #check median/range
pp_check(stan.glm.1, plotfun = "stat_2d", stat = c("mean", "sd"))  
    # Scatterplot of two test statistics (capture the mean somewhat but 
    # sd is kind of bad. at least it's not high sd)
pp_check(stan.glm.1, plotfun = "scatter_avg") # Scatterplot of y vs. average yrep (our model is good for predicting lower # of crimes)
```
```{r}
plot(stan.glm.1, "acf", pars = "crime_rate")# autocorrelation by chain
plot(stan.glm.1, "trace", pars = "crime_rate") #traceplot. how to separate by chain?
```

